Repository MiracleHyehwa/cotree-backend, pull requests merged in 2025-06, with the labels that each got.

#2 [FEAT/#1] 공통 처리 구조 설계
  src/main/java/com/futurenet/cotree/global/dto/response/ApiResponse.java
  src/main/java/com/futurenet/cotree/global/exception/ErrorCode.java
  src/main/java/com/futurenet/cotree/global/exception/RestApiException.java
  src/main/java/com/futurenet/cotree/global/exception/handler/GlobalExceptionHandler.java
Labels: feat

#4 [FEAT] OAuth2 인증/인가 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/futurenet/cotree/auth/config/SecurityConfig.java
  src/main/java/com/futurenet/cotree/auth/constant/JwtConstants.java
  src/main/java/com/futurenet/cotree/auth/controller/AuthController.java
  src/main/java/com/futurenet/cotree/auth/dto/UserAuthDto.java
  src/main/java/com/futurenet/cotree/auth/dto/UserPrincipal.java
  src/main/java/com/futurenet/cotree/auth/dto/request/RefreshTokenSaveRequest.java
  src/main/java/com/futurenet/cotree/auth/exception/AuthErrorCode.java
  src/main/java/com/futurenet/cotree/auth/exception/RefreshTokenException.java
  src/main/java/com/futurenet/cotree/auth/filter/CustomLogoutFilter.java
  src/main/java/com/futurenet/cotree/auth/filter/JwtFilter.java
  src/main/java/com/futurenet/cotree/auth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/futurenet/cotree/auth/oauth2/dto/response/KakaoResponse.java
  src/main/java/com/futurenet/cotree/auth/oauth2/dto/response/OAuth2Response.java
  src/main/java/com/futurenet/cotree/auth/oauth2/handler/CustomOAuth2FailureHandler.java
  src/main/java/com/futurenet/cotree/auth/oauth2/handler/CustomOAuth2SuccessHandler.java
  src/main/java/com/futurenet/cotree/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/futurenet/cotree/auth/repository/RefreshTokenRepository.java
  src/main/java/com/futurenet/cotree/auth/service/JwtService.java
  src/main/java/com/futurenet/cotree/auth/util/JwtUtil.java
  src/main/java/com/futurenet/cotree/auth/util/RequestUtil.java
  src/main/java/com/futurenet/cotree/auth/util/ResponseUtil.java
  src/main/java/com/futurenet/cotree/global/config/WebConfig.java
  src/main/java/com/futurenet/cotree/member/domain/Member.java
  src/main/java/com/futurenet/cotree/member/dto/request/OAuthSignupRequest.java
  src/main/java/com/futurenet/cotree/member/repository/MemberRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/mapper/auth/RefreshTokenMapper.xml
  src/main/resources/mapper/member/MemberMapper.xml
Labels: feat

#20 [FEAT} 카테고리별 상품 조회
  src/main/java/com/futurenet/cotree/item/controller/CategoryController.java
  src/main/java/com/futurenet/cotree/item/controller/ItemController.java
  src/main/java/com/futurenet/cotree/item/dto/ItemDto.java
  src/main/java/com/futurenet/cotree/item/dto/response/CategoryListReponse.java
  src/main/java/com/futurenet/cotree/item/dto/response/ItemResponse.java
  src/main/java/com/futurenet/cotree/item/repository/ItemRepository.java
  src/main/java/com/futurenet/cotree/item/service/CategoryServiceImpl.java
  src/main/java/com/futurenet/cotree/item/service/ItemService.java
  src/main/java/com/futurenet/cotree/item/service/ItemServiceImpl.java
  src/main/resources/mapper/item/CategoryMapper.xml
  src/main/resources/mapper/item/ItemRepository.xml
Labels: feat

#23 [FEAT] 장바구니 삭제 기능
  src/main/java/com/futurenet/cotree/shoppingbasket/controller/ShoppingBasketController.java
  src/main/java/com/futurenet/cotree/shoppingbasket/repository/ShoppingBasketRepository.java
  src/main/java/com/futurenet/cotree/shoppingbasket/service/ShoppingBasketService.java
  src/main/java/com/futurenet/cotree/shoppingbasket/service/ShoppingBasketServiceImpl.java
  src/main/java/com/futurenet/cotree/shoppingbasket/service/exception/ShoppingBasketErrorCode.java
  src/main/resources/mapper/shoppingbasket/ShoppingBasketMapper.xml
Labels: feat, fix

#28 [FEAT] 내 나무 조회
  src/main/java/com/futurenet/cotree/tree/controller/TreeController.java
  src/main/java/com/futurenet/cotree/tree/dto/response/MyTreeResponse.java
  src/main/java/com/futurenet/cotree/tree/repository/TreeRepository.java
  src/main/java/com/futurenet/cotree/tree/service/TreeService.java
  src/main/java/com/futurenet/cotree/tree/service/TreeServiceImpl.java
  src/main/java/com/futurenet/cotree/tree/service/exception/InvalidExpValueException.java
  src/main/java/com/futurenet/cotree/tree/service/exception/TreeCreateFailedException.java
  src/main/java/com/futurenet/cotree/tree/service/exception/TreeErrorCode.java
  src/main/java/com/futurenet/cotree/tree/service/exception/TreeExpUpdateFailedException.java
  src/main/java/com/futurenet/cotree/tree/service/exception/TreeNotFoundException.java
  src/main/resources/mapper/tree/TreeMapper.xml
Labels: feat

#30 [FEAT] 친환경 상품 조회
  src/main/java/com/futurenet/cotree/item/controller/ItemController.java
  src/main/java/com/futurenet/cotree/item/policy/PaginationPolicy.java
  src/main/java/com/futurenet/cotree/item/repository/ItemRepository.java
  src/main/java/com/futurenet/cotree/item/service/ItemService.java
  src/main/java/com/futurenet/cotree/item/service/ItemServiceImpl.java
  src/main/resources/mapper/item/ItemRepository.xml
Labels: feat

#31 FEAT] 주문 등록 기능 구현
  build.gradle
  src/main/java/com/futurenet/cotree/auth/security/config/SecurityConfig.java
  src/main/java/com/futurenet/cotree/auth/security/filter/JwtFilter.java
  src/main/java/com/futurenet/cotree/auth/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/futurenet/cotree/auth/service/JwtServiceImpl.java
  src/main/java/com/futurenet/cotree/auth/service/exception/AuthException.java
  src/main/java/com/futurenet/cotree/auth/service/exception/RefreshTokenException.java
  src/main/java/com/futurenet/cotree/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/futurenet/cotree/item/repository/ItemRepository.java
  src/main/java/com/futurenet/cotree/item/service/ItemService.java
  src/main/java/com/futurenet/cotree/item/service/ItemServiceImpl.java
  src/main/java/com/futurenet/cotree/item/service/exception/ItemErrorCode.java
  src/main/java/com/futurenet/cotree/item/service/exception/ItemException.java
  src/main/java/com/futurenet/cotree/order/controller/OrderController.java
  src/main/java/com/futurenet/cotree/order/dto/request/OrderItemRegisterRequest.java
  src/main/java/com/futurenet/cotree/order/dto/request/OrderRegisterRequest.java
  src/main/java/com/futurenet/cotree/order/dto/request/OrderRequest.java
  src/main/java/com/futurenet/cotree/order/repository/OrderItemRepository.java
  src/main/java/com/futurenet/cotree/order/repository/OrderRepository.java
  src/main/java/com/futurenet/cotree/order/service/OrderFacadeService.java
  src/main/java/com/futurenet/cotree/order/service/OrderFacadeServiceImpl.java
  src/main/java/com/futurenet/cotree/order/service/OrderItemService.java
  src/main/java/com/futurenet/cotree/order/service/OrderItemServiceImpl.java
  src/main/java/com/futurenet/cotree/order/service/OrderService.java
  src/main/java/com/futurenet/cotree/order/service/OrderServiceImpl.java
  src/main/java/com/futurenet/cotree/order/service/exception/OrderErrorCode.java
  src/main/java/com/futurenet/cotree/order/service/exception/OrderException.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V9__create_order_table.sql
  src/main/resources/mapper/item/ItemMapper.xml
  src/main/resources/mapper/order/OrderItemMapper.xml
  src/main/resources/mapper/order/OrderMapper.xml
Labels: feat

#34 [FIX] 회원가입 로직 수정
  src/main/java/com/futurenet/cotree/auth/oauth2/handler/CustomOAuth2FailureHandler.java
  src/main/java/com/futurenet/cotree/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/futurenet/cotree/member/dto/request/OAuthSignupRequest.java
  src/main/java/com/futurenet/cotree/member/repository/MemberRepository.java
  src/main/java/com/futurenet/cotree/member/service/MemberAuthService.java
  src/main/java/com/futurenet/cotree/member/service/MemberAuthServiceImpl.java
  src/main/java/com/futurenet/cotree/member/service/SignupFacadeService.java
  src/main/java/com/futurenet/cotree/member/service/SignupFacadeServiceImpl.java
  src/main/java/com/futurenet/cotree/member/service/exception/MemberErrorCode.java
  src/main/java/com/futurenet/cotree/member/service/exception/MemberException.java
  src/main/resources/db/migration/V10__create_green_point_table.sql
  src/main/resources/mapper/member/MemberMapper.xml
Labels: refactor

#40 [REFACTOR]페이지 네이션 글로벌 설정 및 메서드 이름 변경
  src/main/java/com/futurenet/cotree/global/constant/PaginationConstants.java
  src/main/java/com/futurenet/cotree/item/repository/ItemRepository.java
  src/main/java/com/futurenet/cotree/item/service/ItemServiceImpl.java
  src/main/resources/mapper/item/ItemMapper.xml
Labels: refactor

#43 [FEAT] 결제 기능 구현
  src/main/java/com/futurenet/cotree/greenpoint/constant/GreenPointPolicy.java
  src/main/java/com/futurenet/cotree/greenpoint/dto/GreenPointSaveRequest.java
  src/main/java/com/futurenet/cotree/greenpoint/repository/GreenPointRepository.java
  src/main/java/com/futurenet/cotree/greenpoint/service/GreenPointService.java
  src/main/java/com/futurenet/cotree/greenpoint/service/GreenPointServiceImpl.java
  src/main/java/com/futurenet/cotree/greenpoint/service/exception/GreenPointException.java
  src/main/java/com/futurenet/cotree/item/repository/ItemRepository.java
  src/main/java/com/futurenet/cotree/order/constant/OrderStatus.java
  src/main/java/com/futurenet/cotree/order/repository/OrderRepository.java
  src/main/java/com/futurenet/cotree/order/service/OrderFacadeServiceImpl.java
  src/main/java/com/futurenet/cotree/order/service/exception/OrderErrorCode.java
  src/main/java/com/futurenet/cotree/payment/dto/request/PaymentRegisterRequest.java
  src/main/java/com/futurenet/cotree/payment/dto/request/PaymentRequest.java
  src/main/java/com/futurenet/cotree/payment/dto/request/PaymentRequestEvent.java
  src/main/java/com/futurenet/cotree/payment/dto/response/ItemPriceAndIsEcoResponse.java
  src/main/java/com/futurenet/cotree/payment/handler/PaymentEventHandler.java
  src/main/java/com/futurenet/cotree/payment/repository/PaymentRepository.java
  src/main/java/com/futurenet/cotree/payment/service/PaymentService.java
  src/main/java/com/futurenet/cotree/payment/service/PaymentServiceImpl.java
  src/main/java/com/futurenet/cotree/payment/service/exception/PaymentErrorCode.java
  src/main/java/com/futurenet/cotree/payment/service/exception/PaymentException.java
  src/main/resources/db/migration/V10__create_green_point_table.sql
  src/main/resources/db/migration/V9.1__add_column_payment.sql
  src/main/resources/mapper/greenpoint/GreenPointMapper.xml
  src/main/resources/mapper/item/ItemMapper.xml
  src/main/resources/mapper/order/OrderMapper.xml
  src/main/resources/mapper/payment/PaymentMapper.xml
Labels: feat

#44 [FEAT] 포인트 적립 내역 ,메타 데이터 조회
  src/main/java/com/futurenet/cotree/greenpoint/controller/GreenPointController.java
  src/main/java/com/futurenet/cotree/greenpoint/domain/GreenPoint.java
  src/main/java/com/futurenet/cotree/greenpoint/dto/GreenPointHistoryResponse.java
  src/main/java/com/futurenet/cotree/greenpoint/dto/GreenPointSummaryResponse.java
  src/main/java/com/futurenet/cotree/greenpoint/repository/GreenPointRepository.java
  src/main/java/com/futurenet/cotree/greenpoint/service/GreenPointService.java
  src/main/java/com/futurenet/cotree/greenpoint/service/GreenPointServiceImpl.java
  src/main/resources/mapper/greenpoint/GreenPointMapper.xml
Labels: feat

#48 [FEAT] 마이페이지 조회 기능 구현
  src/main/java/com/futurenet/cotree/auth/security/config/SecurityConfig.java
  src/main/java/com/futurenet/cotree/greenpoint/constant/GreenPointPolicy.java
  src/main/java/com/futurenet/cotree/member/controller/MemberController.java
  src/main/java/com/futurenet/cotree/member/dto/response/MyPageResponse.java
  src/main/java/com/futurenet/cotree/member/repository/MemberRepository.java
  src/main/java/com/futurenet/cotree/member/service/MemberFindService.java
  src/main/java/com/futurenet/cotree/member/service/MemberFindServiceImpl.java
  src/main/java/com/futurenet/cotree/member/service/exception/MemberErrorCode.java
  src/main/java/com/futurenet/cotree/order/constant/OrderStatus.java
  src/main/java/com/futurenet/cotree/order/dto/response/MemberOrderStatusResponse.java
  src/main/java/com/futurenet/cotree/order/repository/OrderRepository.java
  src/main/resources/mapper/member/MemberMapper.xml
  src/main/resources/mapper/order/OrderMapper.xml
Labels: feat

#50 [FEAT] 회원 정보 수정 기능
  build.gradle
  src/main/java/com/futurenet/cotree/global/config/AmazonS3Config.java
  src/main/java/com/futurenet/cotree/global/service/AmazonS3Service.java
  src/main/java/com/futurenet/cotree/member/controller/MemberController.java
  src/main/java/com/futurenet/cotree/member/dto/MemberUpdateAgeAndGenderDto.java
  src/main/java/com/futurenet/cotree/member/dto/MemberUpdateInfoDto.java
  src/main/java/com/futurenet/cotree/member/dto/request/MemberAgeAndGenderRequest.java
  src/main/java/com/futurenet/cotree/member/dto/request/MemberInfoUpdateRequest.java
  src/main/java/com/futurenet/cotree/member/repository/MemberRepository.java
  src/main/java/com/futurenet/cotree/member/service/MemberService.java
  src/main/java/com/futurenet/cotree/member/service/MemberServiceImpl.java
  src/main/java/com/futurenet/cotree/member/service/exception/MemberErrorCode.java
  src/main/resources/mapper/member/MemberMapper.xml
Labels: feat

#54 [FEAT] 장바구니 추가 시 수량체크 및 장바구니 담긴 아이템 개수 조회
  src/main/java/com/futurenet/cotree/shoppingbasket/controller/ShoppingBasketController.java
  src/main/java/com/futurenet/cotree/shoppingbasket/dto/response/ShoppingBasketCountResponse.java
  src/main/java/com/futurenet/cotree/shoppingbasket/repository/ShoppingBasketRepository.java
  src/main/java/com/futurenet/cotree/shoppingbasket/service/ShoppingBasketService.java
  src/main/java/com/futurenet/cotree/shoppingbasket/service/ShoppingBasketServiceImpl.java
  src/main/java/com/futurenet/cotree/shoppingbasket/service/exception/ShoppingBasketErrorCode.java
  src/main/resources/mapper/shoppingbasket/ShoppingBasketMapper.xml
Labels: feat

#52 [FEAT]사용자 활동 로그 저장
  src/main/java/com/futurenet/cotree/item/controller/ItemController.java
  src/main/java/com/futurenet/cotree/item/service/ItemService.java
  src/main/java/com/futurenet/cotree/item/service/ItemServiceImpl.java
  src/main/java/com/futurenet/cotree/member/dto/response/MemberGenderAgeResponse.java
  src/main/java/com/futurenet/cotree/member/repository/MemberRepository.java
  src/main/resources/db/migration/V11__create_user_action_log_table.sql
  src/main/resources/mapper/item/ItemMapper.xml
  src/main/resources/mapper/member/MemberMapper.xml
Labels: feat

#58 [FIX] 로그 폴더 이름 변경
  src/main/java/com/futurenet/cotree/history/dto/request/MemberActionRequestEvent.java
  src/main/java/com/futurenet/cotree/history/handler/MemberActionEventHandler.java
  src/main/java/com/futurenet/cotree/history/repository/LogRepository.java
  src/main/java/com/futurenet/cotree/history/service/MemberActionLogService.java
  src/main/java/com/futurenet/cotree/history/service/MemberActionLogServiceImpl.java
  src/main/java/com/futurenet/cotree/item/service/ItemServiceImpl.java
  src/main/resources/mapper/history/LogRepository.xml
Labels: fix

#60 [FIX] 나이 성별 입력 후 회원 상태 업데이트
  src/main/java/com/futurenet/cotree/member/controller/MemberController.java
  src/main/java/com/futurenet/cotree/member/repository/MemberRepository.java
  src/main/java/com/futurenet/cotree/member/service/MemberServiceImpl.java
  src/main/resources/mapper/member/MemberMapper.xml
Labels: fix

#62 [FIX] 로그인 성공 후 리다이렉트 경로 설정
  src/main/java/com/futurenet/cotree/auth/oauth2/handler/CustomOAuth2SuccessHandler.java
  src/main/java/com/futurenet/cotree/member/repository/MemberRepository.java
  src/main/resources/mapper/member/MemberMapper.xml
Labels: fix

#67 [FIX] 마이페이지 조회 Null 처리
  src/main/java/com/futurenet/cotree/auth/security/config/SecurityConfig.java
  src/main/resources/mapper/member/MemberMapper.xml
Labels: fix

#72 [FEAT] 주문상태 조회
  src/main/java/com/futurenet/cotree/order/controller/OrderController.java
  src/main/java/com/futurenet/cotree/order/domain/Order.java
  src/main/java/com/futurenet/cotree/order/dto/OrderItemDto.java
  src/main/java/com/futurenet/cotree/order/dto/response/OrderItemResponse.java
  src/main/java/com/futurenet/cotree/order/dto/response/OrderResponse.java
  src/main/java/com/futurenet/cotree/order/repository/OrderItemRepository.java
  src/main/java/com/futurenet/cotree/order/repository/OrderRepository.java
  src/main/java/com/futurenet/cotree/order/service/OrderFacadeService.java
  src/main/java/com/futurenet/cotree/order/service/OrderFacadeServiceImpl.java
  src/main/java/com/futurenet/cotree/order/service/OrderItemService.java
  src/main/java/com/futurenet/cotree/order/service/OrderItemServiceImpl.java
  src/main/java/com/futurenet/cotree/order/service/OrderService.java
  src/main/java/com/futurenet/cotree/order/service/OrderServiceImpl.java
  src/main/resources/mapper/order/OrderItemMapper.xml
  src/main/resources/mapper/order/OrderMapper.xml
Labels: feat

#80 [FEAT] 결제 확정
  src/main/java/com/futurenet/cotree/member/service/MemberFindServiceImpl.java
  src/main/java/com/futurenet/cotree/order/domain/Order.java
  src/main/java/com/futurenet/cotree/order/domain/OrderItem.java
  src/main/java/com/futurenet/cotree/order/dto/MemberOrderStatusDto.java
  src/main/java/com/futurenet/cotree/order/dto/request/OrderItemRegisterRequest.java
  src/main/java/com/futurenet/cotree/order/dto/response/OrderDetailResponse.java
  src/main/java/com/futurenet/cotree/order/repository/OrderItemRepository.java
  src/main/java/com/futurenet/cotree/order/repository/OrderRepository.java
  src/main/java/com/futurenet/cotree/order/service/OrderFacadeServiceImpl.java
  src/main/java/com/futurenet/cotree/order/service/OrderItemServiceImpl.java
  src/main/java/com/futurenet/cotree/payment/controller/PaymentController.java
  src/main/java/com/futurenet/cotree/payment/dto/request/PaymentConfirmRequest.java
  src/main/java/com/futurenet/cotree/payment/dto/request/PaymentRequest.java
  src/main/java/com/futurenet/cotree/payment/service/PaymentService.java
  src/main/java/com/futurenet/cotree/payment/service/PaymentServiceImpl.java
  src/main/resources/mapper/order/OrderItemMapper.xml
  src/main/resources/mapper/order/OrderMapper.xml
Labels: feat

#83 [FEAT]오늘의 상품 조회
  src/main/java/com/futurenet/cotree/item/controller/ItemController.java
  src/main/java/com/futurenet/cotree/item/repository/ItemRepository.java
  src/main/java/com/futurenet/cotree/item/service/ItemService.java
  src/main/java/com/futurenet/cotree/item/service/ItemServiceImpl.java
  src/main/resources/mapper/item/ItemMapper.xml
Labels: feat

#89 [FIX] 주문 조회 상태 반환
  src/main/java/com/futurenet/cotree/order/domain/Order.java
  src/main/java/com/futurenet/cotree/order/dto/response/OrderResponse.java
  src/main/resources/mapper/order/OrderMapper.xml
Labels: fix

#98 [FEAT] 관리자 로그인 기능
  src/main/java/com/futurenet/cotree/admin/controller/AdminController.java
  src/main/java/com/futurenet/cotree/admin/repository/AdminRepository.java
  src/main/java/com/futurenet/cotree/admin/service/AdminService.java
  src/main/java/com/futurenet/cotree/admin/service/AdminServiceImpl.java
  src/main/java/com/futurenet/cotree/admin/util/AdminTokenUtil.java
  src/main/java/com/futurenet/cotree/auth/security/filter/JwtFilter.java
  src/main/java/com/futurenet/cotree/auth/util/RequestUtil.java
  src/main/java/com/futurenet/cotree/global/config/AdminInterceptorConfig.java
  src/main/java/com/futurenet/cotree/global/interceptor/AdminInterceptor.java
Labels: feat

#103 [FEAT] 상품 구매 데이터 통계
  src/main/java/com/futurenet/cotree/admin/controller/AdminEcoItemStatisticController.java
  src/main/java/com/futurenet/cotree/admin/dto/response/EcoPurchaseCategoryResponse.java
  src/main/java/com/futurenet/cotree/admin/dto/response/PopularEcoItemResponse.java
  src/main/java/com/futurenet/cotree/admin/repository/AdminEcoItemStatisticRepository.java
  src/main/java/com/futurenet/cotree/admin/service/AdminEcoItemStatisticService.java
  src/main/java/com/futurenet/cotree/admin/service/AdminEcoItemStatisticServiceImpl.java
  src/main/resources/mapper/admin/AdminEcoItemStatisticRepository.xml
Labels: feat

#105 [FIX] 친환경 인기 상품 조회 쿼리 수정
  src/main/resources/mapper/admin/AdminEcoItemStatisticRepository.xml
Labels: fix

#106 [FEAT] 관리자 통계
  src/main/java/com/futurenet/cotree/admin/controller/AdminEcoItemStatisticController.java
  src/main/java/com/futurenet/cotree/admin/repository/AdminEcoItemStatisticRepository.java
  src/main/java/com/futurenet/cotree/admin/service/AdminEcoItemStatisticService.java
  src/main/java/com/futurenet/cotree/admin/service/AdminEcoItemStatisticServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mapper/admin/AdminEcoItemStatisticRepository.xml
Labels: feat

#108 [FIX] cors 설정 변경
  src/main/java/com/futurenet/cotree/auth/security/config/SecurityConfig.java
  src/main/java/com/futurenet/cotree/global/config/WebConfig.java
Labels: fix

#124 [FIX] boolean 필드 JsonProperty 적용
  src/main/java/com/futurenet/cotree/order/dto/request/OrderRequest.java
Labels: fix

#129 [REFACTOR] 주문 조회 페이징 처리
  src/main/java/com/futurenet/cotree/order/controller/OrderController.java
  src/main/java/com/futurenet/cotree/order/repository/OrderRepository.java
  src/main/java/com/futurenet/cotree/order/service/OrderFacadeService.java
  src/main/java/com/futurenet/cotree/order/service/OrderFacadeServiceImpl.java
  src/main/java/com/futurenet/cotree/order/service/OrderService.java
  src/main/java/com/futurenet/cotree/order/service/OrderServiceImpl.java
  src/main/resources/mapper/order/OrderMapper.xml
Labels: refactor

#133 [FIX] prometheus 접근 설정 변경
  prometheus.yml
  src/main/java/com/futurenet/cotree/auth/security/config/SecurityConfig.java
Labels: fix
